// Generated by CoffeeScript 1.12.4
(function() {
  $('button').on('click', function(e) {
    var $box;
    $box = $('.box');
    $box.css('display', 'block');
    if ($box.hasClass('showing') || $box.hasClass('hiding')) {
      return $box.toggleClass('showing hiding');
    } else {
      return $box.addClass('hiding');
    }
  });

  $('.box').on('animationend', function(e) {
    if ($(this).hasClass('hiding')) {
      return $(this).css('display', 'none');
    }
  });

}).call(this);
